---
- name: Update and upgrade packages on dockerhost
  hosts: all
  become: yes
  become_method: sudo
  tasks:
    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Upgrade packages
      ansible.builtin.apt:
        upgrade: dist
