---
# Ansible Playbook to update and upgrade packages on a host
# This playbook performs `sudo apt update` and `sudo apt upgrade` on the specified host.

- name: Update and upgrade packages on dockerhost
  hosts: all
  become: yes  # Ensures the tasks are run with sudo privileges
  vars:
    ansible_host: 192.168.1.101  # IP address of the target host

  tasks:
    - name: Update the apt package index
      apt:
        update_cache: yes

    - name: Upgrade all packages to the latest version
      apt:
        upgrade: dist
