---
- name: List current directory contents on all hosts
  hosts: all
  become: yes
  gather_facts: no
  
  tasks:
    - name: Pull docker images with docker-compose
      become: yes
      ansible.builtin.command:
        cmd: whoami
        chdir: /home/dockerhost/docker_data/arr_stack
      register: compose_pull

    - name: Show output
      ansible.builtin.debug:
        var: compose_pull.stdout_lines

