---
- name: List current directory contents on all hosts
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Pull latest images with Docker Compose
      become: yes
      become_method: sudo
      ansible.builtin.command:
        cmd: docker compose pull
        chdir: /home/dockerhost/docker_data/arr_stack
      register: pull_output

    - name: Start containers with Docker Compose
      become: yes
      become_method: sudo
      ansible.builtin.command:
        cmd: docker compose up -d
        chdir: /home/dockerhost/docker_data/arr_stack
      register: up_output

    - name: Print the output of the pull command
      debug:
        var: pull_output.stdout_lines

    - name: Print the output of the up command
      debug:
        var: up_output.stdout_lines

