---
- name: List current directory contents on all hosts
  hosts: all
  gather_facts: no

  tasks:
    - name: Change directory to arrstack
      command: cd /home/dockerhost/docker_data/arr_stack
      
    - name: Run 'ls' in the current directory
      command: ls
      register: ls_output

    - name: Print the output of 'ls'
      debug:
        var: ls_output.stdout_lines
