---
- name: List current directory contents on all hosts
  hosts: all
  gather_facts: no
  
  tasks:
    - name: Navigate to arr_stack directory and list contents
      shell: |
        cd /home/dockerhost/docker_data/arr_stack
        ls
        pwd
      register: shell_output

    - name: Print the output of the shell command
      debug:
        var: shell_output.stdout_lines

